#pragma once

/* log */
#define APP_LOG_LEVEL 4
#define MR_LOG_LEVEL 4
#define MA_LOG_LEVEL 4

/* task */
#define TASK_PRIORITY_REFLECTOR 20
#define TASK_PRIORITY_ENCODER 7
#define TASK_PRIORITY_IMU 6
#define TASK_PRIORITY_SPEED_CONTROLLER 5
#define TASK_PRIORITY_WALL_DETECTOR 4
#define TASK_PRIORITY_MOVE_ACTION 3
#define TASK_PRIORITY_LED 1
#define TASK_PRIORITY_TOF 1
#define TASK_PRIORITY_BUTTON 1
#define TASK_PRIORITY_BUZZER 1
